### ISSUE TITLE
Database credentials for different Drupal versions

### ISSUE THREAD

**Issue by luispimentellopes** [lando/drupal#16]
Hello,

I'm updating projects between Drupal 8 and 9 versions and I'm struggling with the database.

If I update the recipe to Drupal 9 and do `lando rebuild` it will keep Drupal 8 credentials but if a new dev joins (or I need to destroy the project and start it again) it will create the database credentials with drupal9.

Since the Drupal release cycle is speeding up since Drupal 9 (Drupal 10 is expected to be in June 2022) will it be a good idea to just have "drupal" as credential to every Drupal recipe (or just the future ones) out of the box.

Thanks

**Comment by labboy0276** [comment]
@gitressa Right now, the db creds are created based off the recipe name.  It is the same for all recipes.  If someone wants to put in a PR to change that behavior in this plugin while allowing for existing DB creds to work, I would take a look.

**Comment by gitressa** [comment]
@labboy0276 I see, thanks for clarifying and being open for a PR. Would the code update most likely need to happen in [lando/cli](https://github.com/lando/cli/) or this repo?

**Comment by labboy0276** [comment]
Yes right now it would be either in the cli or the service itself, which would be hard to do in Lando 3.x.  Maybe in 4.x we will decouple this, but for now after I thought about it more, it's probably best to leave it as is.  

If you set the db creds like I stated, then `lando drush site:install --db-url=mysql://drupal:drupal@database/drupal` will work.

**Comment by gitressa** [comment]
I agree, it's probably too much effort and change for too small gain, since it's not urgent, and there is a work-around.

It would be a nice improvement in Lando, so perhaps this issue can be tagged with [4.x](https://github.com/lando/drupal/labels/4.x), same as https://github.com/lando/cli/labels/4.x? I guess a more fitting title then would be something like "Allow defining database credentials at init".

Maybe something like this in Lando `4.x`?

`lando init --recipe=drupal9 --name=drupal9 --db-config="drupal,drupal,drupal"`
