### ISSUE TITLE
why are you ruining php 7.4?

### ISSUE THREAD

**Issue by wp-coin** [lando/drupal#50]
this php version has been deprecated and is no longer recommended

**Comment by pfrenssen** [comment]
It's so that people can still work on legacy projects that need to run on old PHP versions for various reasons that might be outside of the developer's control.

I'm sure you can imagine the hundreds of thousands of sites out there still running Drupal 6 or Drupal 7 on ancient servers with no chance to get a PHP update pushed through because the customer doesn't care or doesn't have the knowledge or resources to do that.

Thanks to the wonders of running PHP in a containerized setup like Lando, developers can still maintain these sites easily on their modern machines.

**Comment by AaronFeledy** [comment]
Exactly right, @pfrenssen
